import React, { useState } from 'react';
import { ChevronDown, ChevronUp, Search } from 'lucide-react';

interface FAQItem {
  question: string;
  answer: string;
  category: string;
}

const FAQ: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  const [searchTerm, setSearchTerm] = useState('');
  const [activeCategory, setActiveCategory] = useState('all');

  const faqItems: FAQItem[] = [
    {
      question: "What is Wordsmith?",
      answer: "Wordsmith is an AI-powered article writing tool that helps you create high-quality content quickly and efficiently. Upload reference materials, set your preferences, and let our AI generate customized articles tailored to your needs.",
      category: "general"
    },
    {
      question: "How does Wordsmith work?",
      answer: "Wordsmith uses advanced AI technology to generate articles based on your inputs. You can upload PDF documents as reference material, specify your desired tone, style, and length, and our AI will create content that matches your requirements while incorporating information from your references.",
      category: "general"
    },
    {
      question: "Is Wordsmith free to use?",
      answer: "Wordsmith offers a free tier that allows you to generate a limited number of articles per month. For more extensive usage, we offer premium subscription plans with additional features and higher usage limits.",
      category: "pricing"
    },
    {
      question: "What subscription plans do you offer?",
      answer: "We offer two premium plans: Basic ($9.99/month) which includes 10 AI-generated articles per month and basic customization options, and Premium ($19.99/month) which offers unlimited articles and advanced customization features.",
      category: "pricing"
    },
    {
      question: "Can I cancel my subscription at any time?",
      answer: "Yes, you can cancel your subscription at any time. Your access will continue until the end of your current billing period, after which it will revert to the free tier.",
      category: "pricing"
    },
    {
      question: "What file formats can I upload as reference material?",
      answer: "Currently, Wordsmith supports PDF documents as reference material. We're working on adding support for more file formats in the future.",
      category: "features"
    },
    {
      question: "How accurate is the content generated by Wordsmith?",
      answer: "Wordsmith strives to generate accurate content based on the reference materials you provide. However, we recommend reviewing and fact-checking the generated content, especially for specialized or technical topics.",
      category: "features"
    },
    {
      question: "Can I edit the generated articles?",
      answer: "Yes, you can edit, download, and save the articles generated by Wordsmith. The content is yours to use as you see fit.",
      category: "features"
    },
    {
      question: "Is my data secure with Wordsmith?",
      answer: "Yes, we take data security seriously. Your uploaded documents and generated content are encrypted and stored securely. We do not share your data with third parties without your consent.",
      category: "security"
    },
    {
      question: "Do I need to create an account to use Wordsmith?",
      answer: "You can try the basic features without an account, but creating a free account allows you to save your generated articles and access them later.",
      category: "general"
    },
    {
      question: "How do I get help if I encounter issues?",
      answer: "You can visit our Support Center for troubleshooting guides, or contact our support team through the Contact page. We aim to respond to all inquiries within 24 hours.",
      category: "support"
    },
    {
      question: "Can I use the generated content commercially?",
      answer: "Yes, you own the rights to the content generated using Wordsmith and can use it for commercial purposes.",
      category: "legal"
    },
    {
      question: "Does Wordsmith support languages other than English?",
      answer: "Currently, Wordsmith primarily supports English content generation. We're working on adding support for more languages in future updates.",
      category: "features"
    },
    {
      question: "How does Wordsmith compare to other AI writing tools?",
      answer: "Wordsmith distinguishes itself through its source-based generation capability, allowing you to upload reference materials that inform the AI's output. We also offer extensive customization options for tone, style, and length that many competitors don't provide.",
      category: "general"
    },
    {
      question: "Can I collaborate with team members on Wordsmith?",
      answer: "Team collaboration features are available on our Premium plan, allowing multiple users to access and work on content under a single account.",
      category: "features"
    }
  ];

  const toggleAccordion = (index: number) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  const categories = [
    { id: 'all', name: 'All Questions' },
    { id: 'general', name: 'General' },
    { id: 'features', name: 'Features' },
    { id: 'pricing', name: 'Pricing' },
    { id: 'security', name: 'Security' },
    { id: 'legal', name: 'Legal' },
    { id: 'support', name: 'Support' }
  ];

  const filteredFAQs = faqItems.filter(item => {
    const matchesSearch = item.question.toLowerCase().includes(searchTerm.toLowerCase()) || 
                          item.answer.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesCategory = activeCategory === 'all' || item.category === activeCategory;
    return matchesSearch && matchesCategory;
  });

  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8 max-w-5xl mx-auto">
      {/* Header */}
      <div className="text-center mb-12">
        <h1 className="text-4xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h1>
        <p className="text-xl text-gray-600 max-w-3xl mx-auto">
          Find answers to common questions about Wordsmith and how it can help you create better content.
        </p>
      </div>

      {/* Search Bar */}
      <div className="mb-8">
        <div className="relative">
          <input
            type="text"
            placeholder="Search for questions..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="w-full px-4 py-3 pl-12 border border-gray-300 rounded-lg focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500"
          />
          <Search className="absolute left-4 top-3.5 h-5 w-5 text-gray-400" />
        </div>
      </div>

      {/* Category Tabs */}
      <div className="mb-8 overflow-x-auto">
        <div className="flex space-x-2 min-w-max">
          {categories.map(category => (
            <button
              key={category.id}
              onClick={() => setActiveCategory(category.id)}
              className={`px-4 py-2 rounded-full text-sm font-medium transition-colors ${
                activeCategory === category.id
                  ? 'bg-indigo-600 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              {category.name}
            </button>
          ))}
        </div>
      </div>

      {/* FAQ Accordion */}
      <div className="space-y-4">
        {filteredFAQs.length > 0 ? (
          filteredFAQs.map((item, index) => (
            <div key={index} className="border border-gray-200 rounded-lg overflow-hidden">
              <button
                onClick={() => toggleAccordion(index)}
                className="flex justify-between items-center w-full px-6 py-4 text-left bg-white hover:bg-gray-50 transition-colors"
              >
                <span className="font-medium text-gray-900">{item.question}</span>
                {activeIndex === index ? (
                  <ChevronUp className="h-5 w-5 text-indigo-600" />
                ) : (
                  <ChevronDown className="h-5 w-5 text-gray-500" />
                )}
              </button>
              {activeIndex === index && (
                <div className="px-6 py-4 bg-gray-50 border-t border-gray-200">
                  <p className="text-gray-700">{item.answer}</p>
                </div>
              )}
            </div>
          ))
        ) : (
          <div className="text-center py-12">
            <p className="text-gray-500">No results found for "{searchTerm}"</p>
            <button
              onClick={() => {
                setSearchTerm('');
                setActiveCategory('all');
              }}
              className="mt-4 text-indigo-600 hover:text-indigo-800"
            >
              Clear search and filters
            </button>
          </div>
        )}
      </div>

      {/* Still Have Questions Section */}
      <div className="mt-16 bg-indigo-50 rounded-lg p-8 text-center">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">Still Have Questions?</h2>
        <p className="text-gray-700 mb-6">
          Can't find the answer you're looking for? Please visit our support center or contact our customer support team.
        </p>
        <div className="flex justify-center gap-4">
          <a 
            href="/support" 
            className="px-6 py-3 bg-white text-indigo-600 font-medium rounded-md border border-indigo-600 hover:bg-indigo-50 transition-colors"
          >
            Visit Support Center
          </a>
          <a 
            href="/contact" 
            className="px-6 py-3 bg-indigo-600 text-white font-medium rounded-md hover:bg-indigo-700 transition-colors"
          >
            Contact Us
          </a>
        </div>
      </div>
    </div>
  );
};

export default FAQ;
