import React from 'react';
import { Shield, AlertCircle } from 'lucide-react';

const PrivacyPolicy: React.FC = () => {
  // Get current date for the "Last Updated" section
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric'
  });

  return (
    <div className="py-16 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      {/* Header */}
      <div className="mb-12">
        <div className="flex items-center justify-center mb-6">
          <Shield className="h-12 w-12 text-indigo-600 mr-4" />
          <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
        </div>
        <p className="text-center text-gray-600">
          Last Updated: {currentDate}
        </p>
      </div>

      {/* Introduction */}
      <div className="prose prose-indigo max-w-none mb-12">
        <p>
          At Wordsmith, we take your privacy seriously. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our website and service (the "Service") operated by Azriel Tech Labs ("we", "us", or "our").
        </p>
        <p>
          Please read this Privacy Policy carefully. By accessing or using the Service, you acknowledge that you have read, understood, and agree to be bound by all the terms of this Privacy Policy. If you do not agree with our policies and practices, please do not use our Service.
        </p>
        <p>
          We may change our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to review this Privacy Policy periodically for any changes.
        </p>
      </div>

      {/* Table of Contents */}
      <div className="bg-gray-50 p-6 rounded-lg mb-12">
        <h2 className="text-xl font-bold text-gray-900 mb-4">Table of Contents</h2>
        <ol className="list-decimal list-inside space-y-2 text-gray-700">
          <li><a href="#information-collect" className="text-indigo-600 hover:text-indigo-800">Information We Collect</a></li>
          <li><a href="#how-we-use" className="text-indigo-600 hover:text-indigo-800">How We Use Your Information</a></li>
          <li><a href="#information-sharing" className="text-indigo-600 hover:text-indigo-800">Information Sharing and Disclosure</a></li>
          <li><a href="#data-security" className="text-indigo-600 hover:text-indigo-800">Data Security</a></li>
          <li><a href="#data-retention" className="text-indigo-600 hover:text-indigo-800">Data Retention</a></li>
          <li><a href="#your-rights" className="text-indigo-600 hover:text-indigo-800">Your Rights and Choices</a></li>
          <li><a href="#children-privacy" className="text-indigo-600 hover:text-indigo-800">Children's Privacy</a></li>
          <li><a href="#international-transfers" className="text-indigo-600 hover:text-indigo-800">International Data Transfers</a></li>
          <li><a href="#cookies" className="text-indigo-600 hover:text-indigo-800">Cookies and Tracking Technologies</a></li>
          <li><a href="#contact-us" className="text-indigo-600 hover:text-indigo-800">Contact Us</a></li>
        </ol>
      </div>

      {/* Privacy Policy Sections */}
      <div className="space-y-12">
        {/* Information We Collect */}
        <section id="information-collect" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">1. Information We Collect</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We collect several types of information from and about users of our Service, including:
            </p>
            
            <h3>Personal Information</h3>
            <p>
              When you register for an account, we collect:
            </p>
            <ul>
              <li>Your name</li>
              <li>Email address</li>
              <li>Password (stored in encrypted form)</li>
              <li>Billing information (if you subscribe to a paid plan)</li>
            </ul>
            
            <h3>Content Information</h3>
            <p>
              When you use our Service, we collect:
            </p>
            <ul>
              <li>Documents you upload as reference materials</li>
              <li>Prompts and parameters you provide for content generation</li>
              <li>Articles and content generated by the Service</li>
            </ul>
            
            <h3>Usage Information</h3>
            <p>
              We automatically collect certain information about your device and how you interact with our Service, including:
            </p>
            <ul>
              <li>IP address</li>
              <li>Browser type and version</li>
              <li>Operating system</li>
              <li>Time and date of your visit</li>
              <li>Pages you view</li>
              <li>Features you use</li>
              <li>Error logs and performance data</li>
            </ul>
            
            <h3>Cookies and Similar Technologies</h3>
            <p>
              We use cookies and similar tracking technologies to track activity on our Service and hold certain information. See our Cookies section below for more details.
            </p>
          </div>
        </section>

        {/* How We Use Your Information */}
        <section id="how-we-use" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">2. How We Use Your Information</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We use the information we collect about you for various purposes, including to:
            </p>
            <ul>
              <li>Provide, maintain, and improve our Service</li>
              <li>Process and complete transactions</li>
              <li>Send you technical notices, updates, security alerts, and support messages</li>
              <li>Respond to your comments, questions, and requests</li>
              <li>Develop new products, services, features, and functionality</li>
              <li>Monitor and analyze trends, usage, and activities in connection with our Service</li>
              <li>Detect, investigate, and prevent fraudulent transactions and other illegal activities</li>
              <li>Personalize and improve your experience with our Service</li>
              <li>Train and improve our AI models (using anonymized data)</li>
            </ul>
            
            <p>
              We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations.
            </p>
          </div>
        </section>

        {/* Information Sharing */}
        <section id="information-sharing" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">3. Information Sharing and Disclosure</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We do not sell, trade, or otherwise transfer your personal information to outside parties except in the following circumstances:
            </p>
            
            <h3>Service Providers</h3>
            <p>
              We may share your information with third-party vendors, service providers, contractors, or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include payment processing, data analysis, email delivery, hosting services, customer service, and marketing efforts.
            </p>
            
            <h3>Business Transfers</h3>
            <p>
              If we are involved in a merger, acquisition, or sale of all or a portion of our assets, your information may be transferred as part of that transaction. We will notify you via email and/or a prominent notice on our Service of any change in ownership or uses of your personal information.
            </p>
            
            <h3>Legal Requirements</h3>
            <p>
              We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena.
            </p>
            
            <h3>Protection of Rights</h3>
            <p>
              We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person, or as evidence in litigation in which we are involved.
            </p>
            
            <h3>With Your Consent</h3>
            <p>
              We may share your information with your consent or at your direction.
            </p>
            
            <h3>Aggregated or De-identified Information</h3>
            <p>
              We may share aggregated or de-identified information, which cannot reasonably be used to identify you, for various purposes including improving our services and AI models.
            </p>
          </div>
        </section>

        {/* Data Security */}
        <section id="data-security" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">4. Data Security</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We have implemented appropriate technical and organizational measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure.
            </p>
            <p>
              All information you provide to us is stored on secure servers behind firewalls. Any payment transactions will be encrypted using SSL technology. Your account is protected by a password. You are responsible for keeping your password confidential.
            </p>
            <p>
              Unfortunately, the transmission of information via the internet is not completely secure. Although we do our best to protect your personal information, we cannot guarantee the security of your personal information transmitted to our Service. Any transmission of personal information is at your own risk.
            </p>
          </div>
        </section>

        {/* Data Retention */}
        <section id="data-retention" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">5. Data Retention</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We will retain your personal information only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your information to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our policies.
            </p>
            <p>
              If you request deletion of your account, we will delete your personal information within 30 days, except for information that we are required to retain for legal or legitimate business purposes.
            </p>
            <p>
              Content you have generated using our Service will be retained in your account until you delete it or request account deletion. After account deletion, we may retain anonymized usage data for analytical purposes.
            </p>
          </div>
        </section>

        {/* Your Rights */}
        <section id="your-rights" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">6. Your Rights and Choices</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              Depending on your location, you may have certain rights regarding your personal information, including:
            </p>
            
            <h3>Access and Update</h3>
            <p>
              You can access and update certain information about your account directly within your account settings.
            </p>
            
            <h3>Data Subject Rights</h3>
            <p>
              Depending on your jurisdiction, you may have the right to:
            </p>
            <ul>
              <li>Access the personal information we have about you</li>
              <li>Correct inaccurate or incomplete information</li>
              <li>Request deletion of your personal information</li>
              <li>Restrict or object to certain processing of your data</li>
              <li>Request portability of your personal information</li>
              <li>Withdraw consent where processing is based on consent</li>
            </ul>
            
            <h3>How to Exercise Your Rights</h3>
            <p>
              To exercise these rights, please contact us using the contact information provided at the end of this Privacy Policy. We may need to verify your identity before responding to your request.
            </p>
            
            <h3>Do Not Track Signals</h3>
            <p>
              Some browsers have a "Do Not Track" feature that signals to websites that you visit that you do not want to have your online activity tracked. Our Service does not currently respond to "Do Not Track" signals.
            </p>
          </div>
        </section>

        {/* Children's Privacy */}
        <section id="children-privacy" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">7. Children's Privacy</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              Our Service is not intended for children under the age of 18. We do not knowingly collect personal information from children under 18. If you are a parent or guardian and you are aware that your child has provided us with personal information, please contact us. If we become aware that we have collected personal information from children without verification of parental consent, we take steps to remove that information from our servers.
            </p>
          </div>
        </section>

        {/* International Transfers */}
        <section id="international-transfers" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">8. International Data Transfers</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              Your information may be transferred to, and maintained on, computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ from those in your jurisdiction.
            </p>
            <p>
              If you are located outside the United States and choose to provide information to us, please note that we transfer the data, including personal information, to the United States and process it there.
            </p>
            <p>
              Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
            </p>
            <p>
              We will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your personal information will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
            </p>
          </div>
        </section>

        {/* Cookies */}
        <section id="cookies" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">9. Cookies and Tracking Technologies</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              We use cookies and similar tracking technologies to track activity on our Service and hold certain information.
            </p>
            
            <h3>What Are Cookies</h3>
            <p>
              Cookies are files with a small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device.
            </p>
            
            <h3>Types of Cookies We Use</h3>
            <ul>
              <li><strong>Essential Cookies:</strong> These cookies are necessary for the Service to function properly and cannot be switched off in our systems.</li>
              <li><strong>Performance Cookies:</strong> These cookies allow us to count visits and traffic sources so we can measure and improve the performance of our Service.</li>
              <li><strong>Functional Cookies:</strong> These cookies enable the Service to provide enhanced functionality and personalization.</li>
              <li><strong>Targeting Cookies:</strong> These cookies may be set through our Service by our advertising partners to build a profile of your interests.</li>
            </ul>
            
            <h3>Your Choices Regarding Cookies</h3>
            <p>
              You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
            </p>
            <p>
              Most web browsers allow some control of most cookies through the browser settings. To find out more about cookies, including how to see what cookies have been set and how to manage and delete them, visit <a href="https://www.allaboutcookies.org" className="text-indigo-600 hover:text-indigo-800">www.allaboutcookies.org</a>.
            </p>
          </div>
        </section>

        {/* Contact Us */}
        <section id="contact-us" className="scroll-mt-24">
          <h2 className="text-2xl font-bold text-gray-900 mb-4">10. Contact Us</h2>
          <div className="prose prose-indigo max-w-none">
            <p>
              If you have any questions about this Privacy Policy, please contact us at:
            </p>
            <p>
              <strong>Email:</strong> privacy@wordsmith.com<br />
              <strong>Address:</strong> 123 Innovation Drive, Suite 400, San Francisco, CA 94103
            </p>
            <p>
              For data subject rights requests or complaints, please email: privacy@wordsmith.com
            </p>
          </div>
        </section>
      </div>

      {/* Disclaimer Notice */}
      <div className="mt-16 bg-yellow-50 border border-yellow-200 rounded-lg p-6">
        <div className="flex items-start">
          <AlertCircle className="h-6 w-6 text-yellow-600 mr-4 flex-shrink-0 mt-1" />
          <div>
            <h3 className="text-lg font-medium text-yellow-800 mb-2">Important Notice</h3>
            <p className="text-yellow-700">
              This Privacy Policy document is provided as a template and should be reviewed by a legal professional before use. It may not cover all legal requirements for your specific business or jurisdiction, particularly regarding data protection regulations such as GDPR, CCPA, or other applicable laws.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PrivacyPolicy;
